---
seed: 1
device: "cuda:0"
dataset: "iclr"
evaluation_algorithm: "direct_prediction"
model_checkpoint: "./model_store/iclr_score_prediction.ckpt"
logging:
  project: automatic_scientific_qm
  name: "section_classifier"
  mode: disabled
  tags: []
