---
seed: 1
device: "cuda:0"
dataset: "iclr"
evaluation_algorithm: "swiss_tournament"
model_checkpoint: "./model_store/iclr_pairwise_comparison.ckpt"
logging:
  project: automatic_scientific_qm
  name: "section_classifier"
  mode: disabled
  tags: []

