---
dataset: neurips
venue_file: "./data/neurips_paperhashes.json"
output_file: "./data/neurips_sakana_evaluation.json"
model: "gpt-4o-2024-08-06"
num_reflections: 5 
num_fs_examples: 1
num_reviews_ensemble: 1
temperature: 0.1